### ISSUE TITLE
Code example possibly missing children? 

### ISSUE THREAD

**Issue by jsltran3** [learn-co-curriculum/react-hooks-children#3]
### Canvas Link

https://learning.flatironschool.com/courses/4618/assignments/160642?module_item_id=344624

### Concern

```
<Example exampleProp="example value">
  <h1>Example header!</h1>
  <p>Some example text</p>
</Example>
```
`If you were to use the above definition of the Example component, you would observe no difference at all: the h1 and p would not be rendered. However, if you inspect the props in Example, you'll notice a new prop has been added: children.`

Hi there! Just looking through this and the example says there's a new prop added for children. The bottom example shows the children where the top doesn't . Not sure if it's intentional but I eventually got the gist. 

### Suggested Changes

If the example should include children, I'd recommend adding it in the example block.

**Comment by lizbur10** [comment]
Hi there! Thanks for providing this feedback. I have expanded the explanation of the children prop to try to clear up the confusion. Please note that you may not see these changes reflected in your Canvas course immediately but you can view them here on GitHub.

Thanks for contributing to the Flatiron School curriculum 💙
